import type User from "types/user";

export const userObjectToFormData = ({
  name,
  username,
  email,
  phone,
  website,
  address,
  company,
}: User) => ({
  name,
  username,
  email,
  phone,
  website,
  companyName: company.name,
  companyCatchPhrase: company.catchPhrase,
  companyBs: company.bs,
  addressCity: address.city,
  addressStreet: address.street,
  addressSuite: address.suite,
  addressZipCode: address.zipcode,
  addressLongitude: address.geo.lng,
  addressLatitude: address.geo.lat,
});

export const formDataToUserObject = ({
  id,
  name,
  username,
  email,
  phone,
  website,
  companyName,
  companyCatchPhrase,
  companyBs,
  addressCity,
  addressStreet,
  addressSuite,
  addressZipCode,
  addressLongitude,
  addressLatitude,
}: ReturnType<typeof userObjectToFormData> & { id: number }) => ({
  id,
  name,
  username,
  email,
  phone,
  website,
  company: {
    name: companyName,
    catchPhrase: companyCatchPhrase,
    bs: companyBs,
  },
  address: {
    city: addressCity,
    street: addressStreet,
    suite: addressSuite,
    zipcode: addressZipCode,
    geo: {
      lng: addressLongitude,
      lat: addressLatitude,
    },
  },
});
